editor/editor/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('submit/welcome/')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^submit/', include('submit.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editor/submit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^team/$', views.team, name='team'),
    url(r'^problems/$', views.problems, name='problems'),
    url(r'^view_results/$', views.view_results, name='view_results'),
    url(r'^add_spare_rows/$', views.add_spare_rows, name='add_spare_rows'),
    url(r'^receive_protocol/$', views.receive_protocol, name='receive_protocol'),
    url(r'^problem/(?P<problem_id>\d+)/$', views.problem, name='problem'),
    url(r'^problem/(?P<problem_id>\d+)/save/$', views.save_problem, name='save_problem'),
    url(r'^problem/(?P<problem_id>\d+)/submit/$', views.submit_problem, name='submit_problem'),
    url(r'^problem/(?P<problem_id>\d+)/submit_custom/$', views.submit_problem_custom, name='submit_problem_custom'),
    url(r'^problem/(?P<problem_id>\d+)/add_lang_row/(?P<lang_code>\d+)/$', views.add_lang_row, name='add_lang_row'),
    url(r'^view/(?P<submit_id>\d+)/$', views.view_submit, name='view_submit'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

editor/submit/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings as django_settings
from django.dispatch import receiver

from submit import constants
from submit.helpers import get_default_custom_input

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_player = models.BooleanField(default=True)
    host = models.CharField(default='0.0.0.0', blank=False, max_length=128)
    port = models.IntegerField(default=12347, blank=False)

    def __str__(self):
        return '(Profile-%s-%s-%s-%s-%s)' % (self.id, self.user, self.is_player, self.host, self.port)

class Problem(models.Model):
    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    title = models.CharField(max_length=128)

    content = RichTextUploadingField()
    variables = models.TextField(default='{}')

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']

class Row(models.Model):
    user = models.ForeignKey(User)
    problem = models.ForeignKey(Problem)
    order = models.IntegerField(default=1)
    lang = models.IntegerField(choices=constants.Language.LANG_CHOICES)
    content = models.CharField(max_length=1000, default='', blank=True)

    def __str__(self):
        return '(Row-%s-%s-%s-%s)' % (self.user, self.problem, self.order, self.lang)

    class Meta:
        unique_together = ('user', 'problem', 'order')

class SpareRow(models.Model):
    user = models.ForeignKey(User)
    lang = models.IntegerField(choices=constants.Language.LANG_CHOICES)

    def __str__(self):
        return '(SpareRow-%s-%s-%s)' % (self.id, self.user, self.lang)

class Task(models.Model):
    user = models.ForeignKey(User)
    problem = models.ForeignKey(Problem)
    solved = models.BooleanField(default=False)
    custom_input = models.TextField(blank=True, default='')

    @property
    def active(self):
        if self.solved:
            return False
        order = self.problem.order
        cnt_solved = Task.objects.filter(user=self.user, solved=True, problem__order__lt=order).count()
        if order <= constants.ACTIVE_PROBLEMS + cnt_solved:
            return True
        return False

    def __str__(self):
        return '(Task-%s-%s-%s-%s)' % (self.id, self.user, self.problem, self.active)

    class Meta:
        unique_together = ('user', 'problem')

class SubmitOutput(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    problem = models.ForeignKey(Problem)
    status = models.CharField(max_length=128, blank=True,
                              choices=constants.ReviewResponse.all_items_as_choices())
    score = models.IntegerField()
    custom = models.BooleanField(default=False)

    def dir_path(self):
        return os.path.join(django_settings.SUBMIT_PATH, 'submits',
                str(self.user.id), str(self.id))
    
    def verbose_response(self):
        return constants.ReviewResponse.verbose(self.status)

    def file_path(self):
        return os.path.join(self.dir_path(), str(self.id) + constants.SUBMITTED_FILE_EXTENSION)

    def lang_path(self):
        return os.path.join(self.dir_path(), str(self.id) + constants.SUBMITTED_LANG_FILE_EXTENSION)

    def custom_input_path(self):
        return os.path.join(self.dir_path(), str(self.id) + constants.SUBMITTED_CUSTOM_INPUT_FILE_EXTENSION)

    def raw_path(self):
        return os.path.join(self.dir_path(), str(self.id) + constants.TESTING_RAW_EXTENSION)

    def protocol_path(self):
        return os.path.join(self.dir_path(), str(self.id) + constants.TESTING_PROTOCOL_EXTENSION)

    def protocol_exists(self):
        return os.path.exists(self.protocol_path())

    def __str__(self):
        return '(Output-%s-%s-%s-%s-%s)' % (self.timestamp, self.user, self.problem, self.status, self.custom)


from django.db.models.signals import post_save, pre_save

@receiver(pre_save, sender=Row)
def pre_save_row(sender, instance, **kwargs):
    lang = int(instance.lang)
    length = constants.Language.LANG_LINE_LENGTH[lang]
    instance.content = instance.content[:length]

@receiver(post_save, sender=Problem)
def save_problem(sender, instance, created, **kwargs):
    if created:
        for user in User.objects.all():
            Task.objects.create(user=user, problem=instance, custom_input=get_default_custom_input(instance))

@receiver(post_save, sender=User)
def save_user(sender, instance, created, **kwargs):
    if created:
        for problem in Problem.objects.all():
            Task.objects.create(user=instance, problem=problem, custom_input=get_default_custom_input(problem))


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

editor/submit/views.py
import sys
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET

from submit.models import Problem, Row, SubmitOutput, SpareRow, Task
from submit import constants
from submit.helpers import write_chunks_to_file, get_default_custom_input
from submit.judge_helpers import (create_submit_and_send_to_judge, parse_protocol)

def index(request):
    return render(request, 'submit/index.html', {})

def welcome(request):
    return render(request, 'submit/welcome.html', {})

def team(request):
    return render(request, 'submit/team.html', {})

def get_active(user):
    active_problems = list(filter(
        lambda task: task.active,
        Task.objects.filter(user=user).order_by('problem__order')
    ))
    if len(active_problems) > 0:
        return {
            'error': None,
            'active_problems': active_problems,
            'no_more_problems': False,
        }

    problems = Problem.objects.all()
    first = problems.first()

    error = None
    no_more_problems = False
    if first is None:
        # ziadne ulohy ani nie su?
        error = "Neexistujú žiadne úlohy!"
    else:
        not_solved = Task.objects.filter(user=user, solved=False)
        no_more_problems = len(not_solved) == 0
    return {
        'error': error,
        'active_problems': active_problems,
        'no_more_problems': no_more_problems,
    }

@login_required
def problems(request):
    user = request.user

    result = get_active(user)

    past_problems = []
    error = result['error']
    active_problems = result['active_problems']
    no_more_problems = result['no_more_problems']

    if error is not None:
        context_dict = {
            'error': error,
        }
        return render(request, 'submit/problems.html', context_dict)

    problems = active_problems
    if no_more_problems:
        past_problems = Task.objects.filter(user=user)
    elif len(active_problems) > 0:
        past_problems = Task.objects.filter(user=user, solved=True).order_by('problem__order')
    context_dict = {
        'past_problems': past_problems,
        'active_problems': problems,
        'error': error,
        'no_more_problems': no_more_problems,
    }
    return render(request, 'submit/problems.html', context_dict)

@login_required
@require_GET
def problem(request, problem_id):
    user = request.user

    result = get_active(user)
    if result['error'] is not None:
        return redirect('problems')

    problem = Problem.objects.get(pk=problem_id)
    task = Task.objects.get(user=user, problem=problem) 
    readonly = not task.active

    # nemaju tu co robit
    if not task.active and not task.solved:
        return redirect('problems')

    rows = Row.objects.filter(problem=problem, user=user).order_by('order')
    submits = SubmitOutput.objects.filter(user=user, problem=problem).order_by('-timestamp')
    lang_counts = SpareRow.objects.filter(user=user).values('lang').annotate(num_rows=Count('lang')).order_by('-num_rows')
    custom_input = Task.objects.get(user=user, problem=problem).custom_input
    variables = None
    try:
        variables = json.loads(problem.variables)
    except json.decoder.JSONDecodeError:
        pass
    context_dict = {
        'problem': problem,
        'rows': rows,
        'readonly': readonly,
        'submits': submits,
        'lang_counts': lang_counts,
        'lang_codes': { code: name for code,name in constants.Language.LANG_CHOICES },
        'lang_length': constants.Language.LANG_LINE_LENGTH,
        'custom_input': custom_input,
        'response': constants.ReviewResponse,
        'variables': variables,
        'custom_example': get_default_custom_input(problem)
    }
    return render(request, 'submit/problem.html', context_dict)

def save_all(request, problem_id):
    user = request.user
    problem = Problem.objects.get(pk=problem_id)
    task = Task.objects.get(user=user, problem=problem) 
    if not task.active:
        return

    rows = Row.objects.filter(problem=problem, user=user).order_by('order')
    for row in rows:
        row.content = request.POST.get('row-%s' % row.order)
        row.save()
    task.custom_input = request.POST.get('custom-input')
    task.save()

@login_required
@require_POST
def add_lang_row(request, problem_id, lang_code):
    user = request.user

    result = get_active(user)
    if result['error'] is not None:
        return redirect('problems')

    problem = Problem.objects.get(pk=problem_id)
    task = Task.objects.get(user=user, problem=problem)

    # nemaju tu co robit
    if not task.active:
        return redirect('problems')

    save_all(request, problem_id)

    spare_row = SpareRow.objects.filter(user=user, lang=lang_code).first()
    if spare_row is None:
        # nemaju taky riadok
        return redirect('problem',  problem_id=problem_id)

    row = Row.objects.filter(user=user, problem=problem).order_by('order').last()
    new_order = 1
    if row is not None:
        new_order = row.order + 1
    Row.objects.create(
            user=user,
            problem=problem,
            order=new_order,
            lang=lang_code,
            content=''
    )
    spare_row.delete()
    return redirect('problem',  problem_id=problem_id)

@login_required
@require_POST
def save_problem(request, problem_id):
    user = request.user

    result = get_active(user)
    if result['error'] is not None:
        return redirect('problems')

    task = Task.objects.get(user=user, problem__id=problem_id) 

    # nemaju tu co robit
    if not task.active:
        return redirect('problems')

    save_all(request, problem_id)

    return redirect('problem',  problem_id=problem_id)

@login_required
@require_POST
def submit_problem(request, problem_id):
    user = request.user

    result = get_active(user)
    if result['error'] is not None:
        return redirect('problems')

    problem = Problem.objects.get(pk=problem_id)
    task = Task.objects.get(user=user, problem=problem) 

    # nemaju tu co robit
    if not task.active:
        return redirect('problems')

    save_all(request, problem_id)

    submit_id = create_submit_and_send_to_judge(problem, user)
    return redirect('view_submit',  submit_id=submit_id)

@login_required
@require_POST
def submit_problem_custom(request, problem_id):
    user = request.user

    result = get_active(user)
    if result['error'] is not None:
        return redirect('problems')

    problem = Problem.objects.get(pk=problem_id)
    task = Task.objects.get(user=user, problem=problem) 

    # nemaju tu co robit
    if not task.active:
        return redirect('problems')

    save_all(request, problem_id)
    task = Task.objects.get(user=user, problem=problem) 

    custom_valid = True
    try:
        json.loads('{ %s }' % task.custom_input)
    except json.decoder.JSONDecodeError:
        custom_valid = False
    print(custom_valid, task.custom_input)

    if custom_valid:
        submit_id = create_submit_and_send_to_judge(problem, user, custom=True)
        return redirect('view_submit',  submit_id=submit_id)
    return redirect('problem',  problem_id=problem_id)

@csrf_exempt
@require_POST
def receive_protocol(request):
    """
    Receive protocol from judge viac POST.
    """
    submit_output_id = request.POST.get('submit_id')
    submit_output = get_object_or_404(SubmitOutput, pk=submit_output_id)
    user = submit_output.user

    task = Task.objects.get(user=user, problem=submit_output.problem)
    if not task.active:
        # nie je to aktivna uloha
        HttpResponse("")

    protocol = request.POST.get('protocol').encode('utf-8')
    write_chunks_to_file(submit_output.protocol_path(), [protocol])

    protocol_data = parse_protocol(submit_output.protocol_path())
    if protocol_data['ready']:
        submit_output.score = protocol_data['score']
        submit_output.status = protocol_data['final_result']
    else:
        submit_output.status = constants.ReviewResponse.PROTOCOL_CORRUPTED
    submit_output.save()

    if submit_output.status == constants.ReviewResponse.OK:
        task.solved = True
        task.save()

    return HttpResponse("")


@login_required
def view_submit(request, submit_id):
    submit = get_object_or_404(SubmitOutput, pk=submit_id)
    is_staff = request.user.is_staff

    if submit.user != request.user and not is_staff:
        raise PermissionDenied()

    context_dict = {
        'submit': submit,
        'response': constants.ReviewResponse,
    }

    with open(submit.file_path(), 'rb') as submitted_file:
        sub_file = submitted_file.read().decode('utf-8', 'replace')
        with open(submit.lang_path(), 'rb') as lang_file:
            file = lang_file.read().decode('utf-8', 'replace')
            order = 1
            rows = []
            for content_line, lang_line in zip(sub_file.split('\n')[:-1], file.split('\n')[:-1]):
                rows.append({
                    'content': content_line,
                    'order': order,
                    'lang': lang_line,
                    })
                order += 1
            context_dict['rows'] = rows

    if submit.protocol_exists():
        force_show_details = is_staff
        context_dict['protocol'] = parse_protocol(submit.protocol_path(), force_show_details)
        context_dict['result'] = constants.JudgeTestResult
    if submit.custom:
        with open(submit.custom_input_path(), 'r') as inp:
            context_dict['custom_input'] = inp.read()

editor/submit/templates/submit/code_rows.html
{% load submit_parts %}

<div class="rows">
    {% for row in rows %}
        <div class="input-group">
            <span class="input-group-addon line-number" id="basic-addon{{ row.order }}">{{ row.order }}</span>
            <input
                type="text"
                class="form-control"
                placeholder="Prečo tu nie je žiaden {{ row.get_lang_display }} kód?!"
                aria-label="Username"
                aria-describedby="basic-addon{{ row.order }}"
                value="{{ row.content }}"
                name="row-{{ row.order }}"
                id="code-row-{{ row.order }}"
                {% if readonly %}readonly=true{% endif %}
                {% if not readonly %}maxlength={{ lang_length | get_key:row.lang  }}{% endif %}
            >
            </input>
            <span class="input-group-addon language" id="basic-addon{{ row.order }}">
                {% if row.get_lang_display is None %}
                    {{row.lang }}
                {% else %}
                    {{ row.get_lang_display }}:{{ lang_length | get_key:row.lang  }}
                {% endif %}
            </span>
        </div>
    {% endfor %}
    {% if rows|length == 0 %}
        <h3 class="empty-code">Prázdny kód.</h3>
        {% if not readonly %}Pridaj riadky.{% endif %}
    {% endif %}
</div>

editor/submit/templates/submit/index.html
{% extends 'submit/main.html' %}

{% block title %}Editor Of Empires{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Editor Of Empires says... hello {{ user.username }}!</h1>
    {% else %}
        <h1>Hello KSP!</h1>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
    {% endif %}
{% endblock %}

editor/submit/templates/submit/problem.html
{% extends 'submit/main.html' %}
{% load submit_parts %}

{% block title %}Úloha: {{ problem.title }}{% endblock %}
{% block content %}

<h2 class="problem-name">{{ problem.title }}</h2>
<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading clickable">
            <h4 class="panel-title">
                <a data-toggle="collapse" href="#collapseStatement{{ problem.id }}">
                    <span>Zadanie</span>
                    <span class="open-close-me">Otvor/Zatvor MA!</span>
                </a>
            </h4>
        </div>
        <div
            id="collapseStatement{{ problem.id }}"
            class="panel-collapse collapse rev-local-collapse"
            style="padding: 10px;"
        >
            {{ problem.content | safe }}
        </div>
    </div>
</div>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading clickable">
            <h4 class="panel-title">
                <a data-toggle="collapse" href="#collapseVariables{{ problem.id }}">
                    <span>Premenné</span>
                    <span class="open-close-me">Otvor/Zatvor MA!</span>
                </a>
            </h4>
        </div>
        <div id="collapseVariables{{ problem.id }}" class="panel-collapse collapse local-collapse">
            <table class="table">
                {% for group_name in variables %}
                    {% if variables|get_key:group_name|length > 0%}
                        <tr>
                            <td>
                                {{ group_name }}
                            </td>
                            <td>
                                {% for variable in variables|get_key:group_name %}
                                    {{ variable }}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<h2>Riešenie:</h2>
<form id="problem_form" method="post" action="">
	{% csrf_token %}
    <p>
        {% include 'submit/code_rows.html' with rows=rows readonly=readonly lang_length=lang_length %}
    </p>
    <p>
        <div class="btn-group" role="group" aria-label="...">
            <button
                type="submit"
                class="btn btn-success"
                {% if readonly %}disabled{% endif %}
                name="save"
                formaction="{% url 'save_problem' problem_id=problem.id %}"
            >
                Save
            </button>
            <button
                type="submit"
                class="btn btn-primary"
                {% if readonly %}disabled{% endif %}
                name="save-submit"
                formaction="{% url 'submit_problem' problem_id=problem.id %}"
            >
                Save & Submit
            </button>
        </div>
    </p>
    <p>
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading clickable">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapseCustomInput{{ problem.id }}">
                            <span>Custom input</span>
                            <span class="open-close-me">Otvor/Zatvor MA!</span>
                        </a>
                    </h4>
                </div>
                <div id="collapseCustomInput{{ problem.id }}" class="panel-collapse collapse local-collapse">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-12">
                                        {
                                        <textarea class="form-control" id="custom-input" name="custom-input" rows="4">{{ custom_input }}</textarea>
                                        }
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="btn-group pull-right" role="group" aria-label="...">
                                            <button
                                                type="submit"
                                                class="btn btn-success"
                                                {% if readonly %}disabled{% endif %}
                                                name="save"
                                                formaction="{% url 'save_problem' problem_id=problem.id %}"
                                            >
                                                Save
                                            </button>
                                            <button
                                                type="submit"
                                                class="btn btn-primary"
                                                {% if readonly %}disabled{% endif %}
                                                name="save-custom-run"
                                                {% if not readonly %}id="save-custom-run"{% endif %}
                                                formaction="{% url 'submit_problem_custom' problem_id=problem.id %}"
                                            >
                                                Save & Run for custom input
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                Example:
                                <pre><code>{{ custom_example }}</code></pre>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </p>
    <div class="row">
        <div class="col col-md-4 col-md-push-8">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            Pridávanie riadkov
                        </h4>
                    </div>
                    <table class="table hover sortable">
                        <thead>
                            <tr>
                                <th>Jazyk</th>
                                <th>Počet</th>
                                <th class="sorttable_nosort">+</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in lang_counts %}
                                <tr>
                                    <td>{{ lang_codes|get_key:row.lang }}</td>
                                    <td>{{ row.num_rows }}</td>
                                    <td>
                                        <button
                                            type="submit"
                                            class="btn btn-success btn-xs"
                                            {% if readonly %}disabled{% endif %}
                                            name="add-lang"
                                            formaction="{% url 'add_lang_row' problem_id=problem.id lang_code=row.lang %}"
                                        >
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col col-md-8 col-md-pull-4">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            Submity
                        </h4>
                    </div>
                    <table class="table hover">
                        <thead>
                            <tr>
                                <th>Čas</th>
                                <th>Stav</th>
                                <th># OK</th>
                                <th>Akcie</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for submit in submits %}
                            <tr class="{% if submit.status == response.OK or submit.status == response.REVIEWED %}
                                        success
                                        {% elif submit.status == response.SENDING_TO_JUDGE or submit.status == response.SENT_TO_JUDGE or submit.status == response.DONE %}
                                        info
                                        {% elif submit.score > 0 %}
                                        warning
                                        {% else %}
                                        danger
                                        {% endif %}">
                                    <td>{{ submit.timestamp|date:"d.m.Y H:i T" }}</td>
                                    <td>{{ submit.get_status_display }}</td>
                                    <td>{{ submit.score }}</td>
                                    <td>
                                        <a
                                            class="btn btn-primary btn-xs"
                                            href="{% url 'view_submit' submit_id=submit.id %}"
                                            target="_blank"
                                        >
                                            Detaily
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
 
{% block js %}
    {{ block.super }}
    <script>
        function isJson(str) {
            try {
                JSON.parse(str);
            } catch (e) {
                return false;
            }
            return true;
        }
        $('#custom-input').bind('input propertychange', function() {
            if (isJson("{" + this.value + "}")) {
                this.classList.remove('invalid');
                this.classList.add('valid');
                $("#save-custom-run").attr("disabled", false);
            } else {
                this.classList.remove('valid');
                this.classList.add('invalid');
                $("#save-custom-run").attr("disabled", true);
            }
        });
        $('.collapse.local-collapse').on('hidden.bs.collapse', function() {
            if (this.id) {
                localStorage.removeItem(this.id);
            }
        }).on('shown.bs.collapse', function() {
            if (this.id) {
                localStorage[this.id] = 'true';
            }
        }).each(function() {
            if (this.id && localStorage[this.id] === 'true' ) {
                $(this).collapse('show');
            } else if (this.id) {
                $(this).collapse('hide');
            }
        });
        $('.collapse.rev-local-collapse').on('hidden.bs.collapse', function() {
            if (this.id) {
                localStorage[this.id] = 'true';
            }
        }).on('shown.bs.collapse', function() {
            if (this.id) {
                localStorage.removeItem(this.id);
            }
        }).each(function() {
            if (this.id && localStorage[this.id] === 'true' ) {
                $(this).collapse('hide');
            } else if (this.id) {
                $(this).collapse('show');
            }
        });
        window.onload = function (e) {
            var inp = $("#custom-input");
            if (isJson("{" + inp.val() + "}")) {
                inp.removeClass('invalid');
                inp.addClass('valid');
                $("#save-custom-run").attr("disabled", false);
            } else {
                inp.removeClass('valid');
                inp.addClass('invalid');
                $("#save-custom-run").attr("disabled", true);
            }
        }
    </script>
{% endblock %}